Support for Dev Pools
dxatscale/sfpowerscripts pull request #544
Opened 2021-06-05 06:21 UTC by azlam-abdulsalam

Fixes #540 

- Major refactor to support dev pools
- Break monolith classes

2021-06-14 22:38 UTC, azlam-abdulsalam commented
@aly76  I believe the distinction between cipool and devppol in the schema could be eliminated depending on the success of 'push' functionality, with pools using push rather than deploy

2021-07-05 02:06 UTC, aly76 requested changes

2021-07-05 02:06 UTC, aly76 commented on packages/sfpowerscripts-cli/package.json
> +    "jsforce": "^1.10.1",
Remove dependency on jsforce

2021-07-05 02:06 UTC, aly76 commented on packages/core/src/logger/SFPLogger.ts
> +  SUCCESS = 70,
Remove LoggerLevel `Success`

2021-07-05 02:06 UTC, aly76 commented on packages/sfpowerscripts-cli/src/SfpowerscriptsCommand.ts
> +      else if(this.flags.loglevel==="FATAL" || this.flags.loglevel==="FATAL")
Typo on condition, should be lowercase

2021-07-05 06:20 UTC, aly76 approved these changes

2021-07-05 06:21 UTC, merged