fix(npm-scope): converts npm scope to lowercase during publish and fetch
dxatscale/sfpowerscripts pull request #833
Opened 2022-02-05 04:28 UTC by azlam-abdulsalam

fix #799

2022-02-07 23:37 UTC, aly76 approved these changes

2022-02-07 23:38 UTC, aly76 requested changes

2022-02-07 23:38 UTC, aly76 commented on packages/sfpowerscripts-cli/src/impl/artifacts/FetchAnArtifactFromNPM.ts
> +        cmd = `npm pack @${this.scope.toLocaleLowerCase()}/${packageName}_sfpowerscripts_artifact`;
wrong method

2022-02-09 04:38 UTC, azlam-abdulsalam reviewed
Changed

2022-02-09 04:38 UTC, azlam-abdulsalam commented on packages/sfpowerscripts-cli/src/impl/artifacts/FetchAnArtifactFromNPM.ts
> +        cmd = `npm pack @${this.scope.toLocaleLowerCase()}/${packageName}_sfpowerscripts_artifact`;
```suggestion
        cmd = `npm pack @${this.scope.toLowerCase()}/${packageName}_sfpowerscripts_artifact`;
```

2022-02-09 04:43 UTC, aly76 approved these changes

2022-02-09 04:43 UTC, merged