refactor(package-list): refactor to use query instead of wrapping around sfdx force:package:list
dxatscale/sfpowerscripts pull request #850
Opened 2022-02-22 04:12 UTC by azlam-abdulsalam

2022-02-22 04:45 UTC, aly76 requested changes, later dismissed

2022-02-22 04:45 UTC, aly76 commented on packages/core/src/package/packageQuery/PackageFetcher.ts
> +    let records = await QueryHelper.query<any>(query, this.conn, true);
Record type should be provided as type parameter, instead of `any`, so that the accessible fields on the `Package2` object are known.

2022-02-22 07:14 UTC, aly76 approved these changes

2022-02-22 08:16 UTC, merged

2022-02-22 18:59 UTC, vuha-acn reviewed
@azlam-abdulsalam  - For each new salesforce release, do we need to update the API Version (eg. v53.0) each time and regression test since is dynamic? Can we have global variable to control this to update in 1 single place instead?

2022-02-28 11:08 UTC, azlam-abdulsalam commented
@vuha-acn We don't use api version (unless in tests), it is set to whatever the target api version if the org is