refactor/apex tests
dxatscale/sfpowerscripts pull request #876
Opened 2022-03-04 00:35 UTC by azlam-abdulsalam

- Unstable commit
- Attempt 2 : Move to all local for testing
- refactor(apex-tests): use apex-node and remove dependency on executing cli
- refactor(apex-test): deprecate synchronous mode

2022-03-07 22:01 UTC, aly76 requested changes

2022-03-07 22:01 UTC, aly76 commented on packages/core/src/apextest/TriggerApexTests.ts
> +                if (runStatus.Status == `Completed` || runStatus.Status == `Cancelled`) break;
The possible Status values are:
- Queued
- Processing
- Aborted
- Completed
- Failed

2022-03-07 22:01 UTC, aly76 commented on packages/core/src/apextest/TriggerApexTests.ts
> +
should shutdown gracefully on interrupt/terminate signal by cancelling async job

2022-03-07 22:01 UTC, aly76 commented on packages/core/src/apextest/TriggerApexTests.ts
> +                    }  Elapsed Time so far: ${Math.floor(Date.now() - startTime) / 1000}`,
Need units for time

2022-03-07 22:01 UTC, aly76 commented on packages/core/src/apextest/TriggerApexTests.ts
> +                if (runStatus.Status == `Completed` || runStatus.Status == `Cancelled`) break;
Need to handle Aborted, Completed and Failed, else an infinite loop may occur

2022-03-07 22:01 UTC, aly76 commented on packages/core/src/apextest/TriggerApexTests.ts
> +                jsonOutput.coverage.coverage,
The result files do not match those created by the CLI.

- `test-result-${testRunId}-codecoverage.json` maps to `TestResult.perClassCoverage`
- `test-result-codecoverage.json` maps to `CLIJsonFormat.coverage.coverage` or an empty array
- `test-result-${testRunId}.json` maps to TestResult
- `test-run-id.txt` maps to TestRunId

2022-03-07 22:01 UTC, aly76 commented on packages/core/tests/sfpcommands/TriggerApexTestSpecifiedTests.test.ts
> -import { jest, expect } from '@jest/globals';
New test class should be written with appropriate mocks for test service and test result

2022-03-07 22:01 UTC, aly76 commented on packages/core/tests/sfpcommands/TriggerApexTestApexTestInPackage.test.ts
> -import { jest, expect } from '@jest/globals';
New test class should be written

2022-03-07 22:01 UTC, aly76 commented on packages/core/src/apextest/TriggerApexTests.ts
> +            while (true) {
Unable to interrupt while loop with signal

2022-03-08 02:38 UTC, azlam-abdulsalam commented on packages/core/tests/sfpcommands/TriggerApexTestSpecifiedTests.test.ts
> -import { jest, expect } from '@jest/globals';
Will be introducing this at later point, as I think it not necessary anymore, as we are using apex-node directly

2022-03-08 02:38 UTC, azlam-abdulsalam commented on packages/core/tests/sfpcommands/TriggerApexTestSpecifiedTests.test.ts
> -import { jest, expect } from '@jest/globals';
Will be introducing this at later point, as I think it not necessary anymore, as we are using apex-node directly

2022-03-08 02:38 UTC, azlam-abdulsalam commented on packages/core/tests/sfpcommands/TriggerApexTestApexTestInPackage.test.ts
> -import { jest, expect } from '@jest/globals';
Will be introducing this at later point, as I think it not necessary anymore, as we are using apex-node directly

2022-03-08 02:38 UTC, azlam-abdulsalam commented on packages/core/tests/sfpcommands/TriggerApexTestApexTestInPackage.test.ts
> -import { jest, expect } from '@jest/globals';
Will be introducing this at later point, as I think it not necessary anymore, as we are using apex-node directly

2022-03-08 12:04 UTC, azlam-abdulsalam commented on packages/core/src/apextest/TriggerApexTests.ts
> +                if (runStatus.Status == `Completed` || runStatus.Status == `Cancelled`) break;
fixed to use reporter instead of using polling

2022-03-08 12:09 UTC, azlam-abdulsalam commented on packages/core/src/apextest/TriggerApexTests.ts
> +                jsonOutput.coverage.coverage,
We will deviate from CLI here, we will provide the following files
 - test-result-${testRunId}-codecoverage.json maps to CLIJsonFormat.coverage.coverage or an empty array
 - test-result-${testRunId}.json maps to TestResult
 - test-result-${testRunId}-junit.xml with junit report

2022-03-09 23:02 UTC, aly76 requested changes

2022-03-09 23:02 UTC, aly76 commented on packages/core/src/apextest/TriggerApexTests.ts
> +                JSON.stringify(testResult),
`writeJSONSync` expects an object and not a string

2022-03-09 23:02 UTC, aly76 commented on packages/core/src/apextest/TriggerApexTests.ts
> +                jsonOutput.coverage.coverage,
The filename being used doesn't match your comment: `test-result-${testRunResult.testRunId}-coverage.json`

2022-03-10 00:02 UTC, azlam-abdulsalam commented on packages/core/src/apextest/TriggerApexTests.ts
> +                JSON.stringify(testResult),
```suggestion
                testResult,
```

2022-03-10 00:32 UTC, merged